OK

diff --git a/.github/workflows/ubuntu-deploy.yml b/.github/workflows/ubuntu-deploy.yml
--- a/.github/workflows/ubuntu-deploy.yml
+++ b/.github/workflows/ubuntu-deploy.yml
@@ -21,8 +21,8 @@ jobs:
           sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
             echo "🚀 Connected to VPS Successfully!"
             cd /html-to-liquid/
-            chmod +x ./.scripts/deploy.sh
+            chmod +x /html-to-liquid/.scripts/deploy.sh
             echo "🚀 Running deployment script..."
-            ./.scripts/deploy.sh || { echo "❌ Deployment Failed!"; exit 1; }
+            /html-to-liquid/.scripts/deploy.sh || { echo "❌ Deployment Failed!"; exit 1; }
             echo "✅ Deployment Complete!"
           EOF
