OK

diff --git a/.github/workflows/ubuntu-deploy.yml b/.github/workflows/ubuntu-deploy.yml
--- a/.github/workflows/ubuntu-deploy.yml
+++ b/.github/workflows/ubuntu-deploy.yml
@@ -21,9 +21,9 @@ jobs:
           sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
             echo "🚀 Connected to VPS Successfully!"
             ls
-            cd /html-to-liquid/
-            chmod +x ./.scripts/deploy.sh
+            cd html-to-liquid/
+            chmod +x .scripts/deploy.sh
             echo "🚀 Running deployment script..."
-            ./.scripts/deploy.sh || { echo "❌ Deployment Failed!"; exit 1; }
+            .scripts/deploy.sh || { echo "❌ Deployment Failed!"; exit 1; }
             echo "✅ Deployment Complete!"
           EOF
